export const capabilities = [
  { n: '01', title: 'Backend Engineering', summary: 'APIs, services, and resilient workflows.', tech: ['Node.js','TypeScript','Express.js','ASP.NET','Django','REST','GraphQL','JWT','OAuth2','Webhooks','Queues','Microservices'] },
  { n: '02', title: 'Frontend Engineering', summary: 'Product interfaces with performance built in.', tech: ['React.js','Next.js','React Native','Tailwind CSS','Redux Toolkit','shadcn/ui'] },
  { n: '03', title: 'Data & Infrastructure', summary: 'Schemas, retrieval, caching, and events.', tech: ['PostgreSQL','MySQL','MongoDB','SQL Server','Prisma','Firebase','pgvector','Redis','Valkey','Kafka'] },
  { n: '04', title: 'AI & Search', summary: 'Useful intelligence grounded in real data.', tech: ['OpenAI API','RAG','Embeddings','Vector Search','LLM Applications','Hugging Face','Ollama','Algolia'] },
  { n: '05', title: 'Cloud & DevOps', summary: 'From local container to production cloud.', tech: ['AWS','GCP','Docker','Git','GitHub','CI/CD','Postman','Swagger'] },
];

export const roles = [
 { period:'DEC 2024 — NOW', company:'Xponent Infosys Pvt. Ltd.', role:'Full Stack Software Engineer', copy:'Building ERP, LMS, and SaaS products across multi-tenant architecture, database optimization, and production systems.', stack:'NODE · TYPESCRIPT · NEXT · PRISMA · POSTGRESQL · MONGODB · AWS' },
 { period:'MAY 2024 — DEC 2025', company:'GlobalTech Information Systems', role:'Full Stack Developer · Part-time', copy:'Enterprise applications, APIs, reporting, authentication, RBAC, and SQL optimization.', stack:'ASP.NET · C# · REACT · SQL SERVER · MYSQL' },
 { period:'JAN 2024 — SEP 2024', company:'Vimi.tv', role:'Full Stack Developer · Remote, USA', copy:'Platform features, cron jobs, automated workflows, content delivery, backend services, deployment, and maintenance.', stack:'NEXT · NODE · FIREBASE · GCP' },
 { period:'FEB 2020 — SEP 2023', company:'Bohni Pvt. Limited', role:'Full Stack Web & Mobile Developer · Remote, India', copy:'Web and mobile applications, reusable interfaces, REST APIs, search, caching, testing, and deployment.', stack:'REACT · REACT NATIVE · NODE · FIREBASE · REDIS · ALGOLIA' },
];

export const projects = [
 {id:'01', name:'UpRankly', type:'SEO SAAS PLATFORM', desc:'SEO automation, outreach and content workflows backed by durable asynchronous processing.', challenge:'Coordinate billing, lifecycle events, and concurrent background work without duplicate queue execution.', solution:'Stripe webhooks, Kafka-driven jobs, Redis, PostgreSQL, and explicit concurrency handling.', stack:'NEXT.JS · EXPRESS · TYPESCRIPT · PRISMA · POSTGRESQL · REDIS · KAFKA · AWS', tone:'lime'},
 {id:'02', name:'Enterprise ERP', type:'BUSINESS OPERATING SYSTEM', desc:'An integrated suite spanning HR, payroll, inventory, procurement, accounting, reporting, and customer management.', challenge:'Model transactional business workflows while keeping complex reporting responsive.', solution:'Structured PostgreSQL architecture, indexes, query optimization, and carefully bounded module workflows.', stack:'NEXT.JS · NODE.JS · TYPESCRIPT · PRISMA · POSTGRESQL · AWS', tone:'sand'},
 {id:'03', name:'Prayogik LMS', type:'LEARNING PLATFORM', desc:'Connected student, instructor, and administration workflows in one learning product.', challenge:'Reliably turn external payment events into verified enrollment state.', solution:'bKash and SSLCommerz integrations, webhook verification, caching, and query/frontend optimization.', stack:'NEXT.JS · NODE.JS · TYPESCRIPT · PRISMA · MONGODB · AWS · OPENAI', tone:'blue'},
 {id:'04', name:'Private AI Assistant', type:'RAG / DOCUMENT INTELLIGENCE', desc:'Private document retrieval from ingestion through grounded LLM response.', challenge:'Make unstructured documents semantically searchable while keeping the system self-hostable.', solution:'Chunking and embeddings stored in pgvector, semantic retrieval, and local inference through Ollama.', stack:'NEXT.JS · TYPESCRIPT · POSTGRESQL · PRISMA · PGVECTOR · HUGGING FACE · OLLAMA · DOCKER', tone:'violet'},
 {id:'05', name:'Podium School', type:'WEB + MOBILE EDUCATION', desc:'A web and mobile education platform designed around reusable product components.', challenge:'Deliver fast discovery and consistent experiences across web and mobile.', solution:'Shared component thinking with Redis caching, Algolia search, and GCP deployment.', stack:'REACT · REACT NATIVE · REDIS · ALGOLIA · GCP', tone:'orange'},
 {id:'06', name:'Bitumen Order System', type:'GOVERNMENT ORDER MANAGEMENT', desc:'Order processing, approval workflows, reports, and administrative control.', challenge:'Encode permission-sensitive enterprise workflows and reporting.', solution:'Authenticated APIs, RBAC, optimized SQL, and explicit approval stages.', stack:'ASP.NET · C# · REACT.JS · SQL SERVER · MYSQL', tone:'red'},
];
