'use client';

import { useEffect, useRef, useState } from 'react';
import { ArrowDown, ArrowUpRight, Menu, X } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import { capabilities, projects, roles } from './data';

gsap.registerPlugin(ScrollTrigger);

function MagneticLink({ href, children, className='' }: {href:string; children:React.ReactNode; className?:string}) {
 const ref=useRef<HTMLAnchorElement>(null);
 return <a ref={ref} href={href} className={`magnetic ${className}`} onMouseMove={(e)=>{if(matchMedia('(pointer:fine)').matches){const r=ref.current!.getBoundingClientRect();gsap.to(ref.current,{x:(e.clientX-r.left-r.width/2)*.18,y:(e.clientY-r.top-r.height/2)*.18,duration:.3})}}} onMouseLeave={()=>gsap.to(ref.current,{x:0,y:0,duration:.5,ease:'power3.out'})}>{children}</a>
}

function Navbar(){
 const [open,setOpen]=useState(false);
 return <><header className="nav"><a href="#top" className="brand">SD<span>®</span></a><nav>{['About','Work','Stack','AI'].map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><MagneticLink href="#contact" className="nav-contact">LET’S TALK <ArrowUpRight size={14}/></MagneticLink><button className="menu" onClick={()=>setOpen(!open)} aria-expanded={open} aria-label="Toggle navigation">{open?<X/>:<Menu/>}</button></header><div className={`mobile-nav ${open?'open':''}`}>{['About','Work','Stack','AI','Contact'].map((x,i)=><a key={x} href={`#${x.toLowerCase()}`} onClick={()=>setOpen(false)}><small>0{i+1}</small>{x}</a>)}</div></>
}

function Cursor(){
 const dot=useRef<HTMLDivElement>(null), ring=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!matchMedia('(pointer:fine)').matches)return; let x=0,y=0,rx=0,ry=0,raf=0; const move=(e:MouseEvent)=>{x=e.clientX;y=e.clientY;dot.current!.style.transform=`translate(${x}px,${y}px)`}; const tick=()=>{rx+=(x-rx)*.14;ry+=(y-ry)*.14;ring.current!.style.transform=`translate(${rx}px,${ry}px)`;raf=requestAnimationFrame(tick)};tick();addEventListener('mousemove',move); const els=document.querySelectorAll('a,button,.project');els.forEach(e=>e.addEventListener('mouseenter',()=>ring.current?.classList.add('active')));els.forEach(e=>e.addEventListener('mouseleave',()=>ring.current?.classList.remove('active')));return()=>{removeEventListener('mousemove',move);cancelAnimationFrame(raf)}} ,[]);
 return <><div ref={dot} className="cursor-dot"/><div ref={ring} className="cursor-ring"/></>
}

function Hero(){return <section id="top" className="hero"><div className="hero-grid"/><div className="eyebrow hero-reveal"><span className="pulse"/>AVAILABLE FOR SELECT OPPORTUNITIES <span>CHITTAGONG, BD</span></div><h1><span className="line"><i>SOURAV</i></span><span className="line indent"><i>DAS</i><b>FULL STACK<br/>SOFTWARE ENGINEER</b></span></h1><div className="hero-bottom hero-reveal"><p>Building scalable products, intelligent systems, and high-performance digital experiences.</p><div className="meta"><span>5+ YEARS</span><span>AI / RAG</span><span>SYSTEMS</span><span>PRODUCT ENGINEERING</span></div></div><a href="#about" className="scroll"><ArrowDown size={16}/>SCROLL TO EXPLORE</a></section>}

function Intro(){return <section id="about" className="intro section"><div className="section-label"><span>01</span><b>IDENTITY / APPROACH</b></div><div className="intro-copy reveal"><p>FULL-STACK ENGINEER BUILDING PRODUCTS FROM <em>DATABASE SCHEMA</em> TO <em>INTERFACE.</em></p></div><div className="intro-side reveal"><p>Sourav brings 5+ years of experience across ERP, SaaS, LMS, web, mobile, and AI-powered applications.</p><p>Product-aware engineering with depth in architecture, data, performance, distributed processing, and usable interfaces.</p></div></section>}

function Capabilities(){const [active,setActive]=useState(0);return <section id="stack" className="capabilities section"><div className="section-label light"><span>02</span><b>ENGINEERING CAPABILITIES</b></div><div className="cap-grid"><div><h2>One product.<br/><em>Every layer.</em></h2><p className="muted">Select a discipline to inspect the toolkit.</p></div><div className="cap-list">{capabilities.map((c,i)=><button key={c.title} className={active===i?'active':''} onMouseEnter={()=>setActive(i)} onFocus={()=>setActive(i)}><span>{c.n}</span><strong>{c.title}</strong><p>{c.summary}</p><b>↗</b></button>)}</div></div><div className="tech-marquee" aria-live="polite"><div>{capabilities[active].tech.map(t=><span key={t}>{t}</span>)}</div></div></section>}

function Experience(){return <section className="experience section"><div className="section-label"><span>03</span><b>EXPERIENCE / TRAJECTORY</b></div><h2 className="display reveal">SYSTEMS BUILT<br/>IN THE <em>REAL WORLD.</em></h2><div className="roles">{roles.map((r,i)=><article className="role reveal" key={r.company}><div className="role-num">0{i+1}</div><div><small>{r.period}</small><h3>{r.company}</h3><b>{r.role}</b></div><p>{r.copy}</p><small className="role-stack">{r.stack}</small></article>)}</div></section>}

function Projects(){return <section id="work" className="work section"><div className="section-label light"><span>04</span><b>SELECTED SYSTEMS / 2020—NOW</b></div><h2 className="work-title reveal">WORK THAT<br/><em>WORKS.</em></h2><div className="projects">{projects.map(p=><article className={`project ${p.tone}`} key={p.id}><div className="project-visual"><span>{p.id}</span><div className="orbit"><i/><i/><i/></div><b>{p.type}</b></div><div className="project-body"><small>{p.id} / 06</small><h3>{p.name}</h3><p className="project-desc">{p.desc}</p><div className="project-detail"><div><b>THE CHALLENGE</b><p>{p.challenge}</p></div><div><b>THE APPROACH</b><p>{p.solution}</p></div></div><div className="stackline">{p.stack}</div></div></article>)}</div></section>}

const stages=['DOCUMENT','INGESTION','CHUNKING','EMBEDDINGS','VECTOR STORAGE','SEMANTIC SEARCH','RETRIEVAL','LLM','RESPONSE'];
function AISection(){return <section id="ai" className="ai section"><div className="section-label"><span>05</span><b>PRIVATE AI / ARCHITECTURE</b></div><div className="ai-head reveal"><h2>KNOWLEDGE,<br/><em>RETRIEVED.</em></h2><p>A private document search engine that turns raw files into grounded, context-aware responses. Designed for local inference and controlled data.</p></div><div className="pipeline">{stages.map((s,i)=><div className="node" key={s}><span>{String(i+1).padStart(2,'0')}</span><b>{s}</b>{i<stages.length-1&&<i>→</i>}</div>)}</div><div className="simulation reveal"><div className="sim-top"><span className="pulse"/> ARCHITECTURAL VISUALIZATION <b>NOT A LIVE CHATBOT</b></div><div className="query"><small>USER QUERY</small><p>“Find relevant information in my private documents.”</p></div><div className="sim-flow">{['Embedding created','Vector similarity search','Relevant chunks retrieved','Context sent to local LLM','Grounded response'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b></div>)}</div></div></section>}

function Surface(){let items=['Multi-tenant systems','Database indexing','Query optimization','Caching','Background jobs','Kafka','Redis','Webhooks','Payment workflows','Authentication','RBAC','Vector search','RAG','Docker','Cloud deployment'];return <section className="surface section"><div className="section-label light"><span>06</span><b>UNDER THE SURFACE</b></div><h2 className="reveal">THE INTERFACE IS ONLY<br/>THE <em>VISIBLE LAYER.</em></h2><div className="surface-grid">{items.map((x,i)=><div key={x} className="surface-item"><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><i/></div>)}</div></section>}

function Footer(){return <><section className="philosophy section"><div className="section-label"><span>07</span><b>OPERATING PRINCIPLES</b></div>{['BUILD FOR THE PRODUCT.','DESIGN THE SYSTEM.','MEASURE THE BOTTLENECK.','KEEP COMPLEXITY INTENTIONAL.'].map((x,i)=><p className="reveal" key={x}><span>0{i+1}</span>{x}</p>)}<div className="education"><span>EDUCATION</span><b>B.Sc. in Computer Science & Engineering</b><p>Port City International University · 2013—2017</p></div></section><footer id="contact"><div className="section-label light"><span>08</span><b>CONTACT / START A CONVERSATION</b></div><h2>LET’S BUILD<br/><em>SOMETHING.</em></h2><p>Have a product, platform, or technical challenge in mind?</p><MagneticLink href="mailto:souravdas14.dev@gmail.com" className="email">souravdas14.dev@gmail.com <ArrowUpRight/></MagneticLink><div className="footer-bottom"><div><small>GITHUB</small><a href="https://github.com/souravdasdip" target="_blank">github.com/souravdasdip</a></div><div><small>PHONE</small><a href="tel:+8801521487521">+880-1521487521</a></div><div><small>LOCATION</small><span>Chattogram, Bangladesh</span></div><div><small>LOCAL TIME</small><span>UTC +06:00</span></div></div><div className="copyright">© 2026 SOURAV DAS <a href="#top">BACK TO TOP ↑</a></div></footer></>}

export default function Home(){
 const root=useRef<HTMLElement>(null);
 useEffect(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced)return;const lenis=new Lenis({duration:1.1,smoothWheel:true});lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(t=>lenis.raf(t*1000));gsap.ticker.lagSmoothing(0);const ctx=gsap.context(()=>{gsap.timeline().from('.hero-grid',{opacity:0,duration:.4}).from('.hero h1 i',{yPercent:110,duration:.8,stagger:.1,ease:'power4.out'},.1).from('.hero-reveal,.scroll',{opacity:0,y:16,duration:.5,stagger:.08},.45);gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{scrollTrigger:{trigger:el,start:'top 86%'},y:50,opacity:0,duration:.8,ease:'power3.out'}));gsap.utils.toArray<HTMLElement>('.node').forEach((el,i)=>gsap.from(el,{scrollTrigger:{trigger:'.pipeline',start:'top 75%'},opacity:.18,scale:.94,duration:.4,delay:i*.08}));},root);return()=>{ctx.revert();lenis.destroy();gsap.ticker.remove(t=>lenis.raf(t*1000))}},[]);
 return <main ref={root}><Cursor/><Navbar/><div className="progress"/><Hero/><Intro/><Capabilities/><Experience/><Projects/><AISection/><Surface/><Footer/></main>
}
